### ISSUE TITLE
Nenaudojamas kodas

### ISSUE THREAD

**Issue by Viliuskerutis** [QuizAppTesting/QuizApp#15]
![image](https://user-images.githubusercontent.com/32612736/68995885-7ab72f00-089b-11ea-9662-e2c1c5ed1e18.png)

**Comment by Viliuskerutis** [comment]
@developer-quizapp šis kodo elementas tikrai nėra naudojamas programos klasių ir ar tikrai nebus naudojamas ateityje implementuojant kitą funkcionalumą ?

**Comment by developer-quizapp** [comment]
Pažymėtas kodo fragmentas gali būti pašalintas. Jis buvo naudojamas implementuojant dabartinį funkcionalumą, tačiau po pakeitimų tapo nereikalingas ir buvo užmirštas pašalinti.

**Comment by Viliuskerutis** [comment]
Nenaudojamas kodas ištrintas: https://github.com/QuizAppTesting/QuizApp/commit/1feba23ba140ea84df6b9d16b739d96b3afbb3fd

**Comment by Viliuskerutis** [comment]
Nenaudojamas kodas ištrintas: https://github.com/QuizAppTesting/QuizApp/commit/1feba23ba140ea84df6b9d16b739d96b3afbb3fd
